feat: initial setup for local development

diff --git a/bin/env b/bin/env
--- a/bin/env
+++ b/bin/env
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.10 (https://bashly.dev)
+# This script was generated by bashly 1.2.9 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -32,10 +32,11 @@ env_usage() {
   printf "  %s   simple alias to docker-compose down\n" "down       "
   printf "  %s   removes the existing container image\n" "clean      "
   printf "  %s   simple alias to docker-compose logs (All docker command options are valid)\n" "logs       "
-  printf "  %s   builds the docker image for local testing\n" "build      "
+  printf "  %s   Installs the npm dependencies and builds the library for local use\n" "build      "
   printf "  %s   rebuilds the bashly application you are currently using, based on the sources\n" "rebuild-cli"
   printf "  %s   basically your docker-compose exec into the main app container\n" "ssh        "
   printf "  %s   runs a certain npm command for the project\n" "npm        "
+  printf "  %s   opens the project in the browser\n" "open       "
   echo
 
   # :command.long_usage
@@ -212,7 +213,7 @@ env_logs_usage() {
 
 # :command.usage
 env_build_usage() {
-  printf "env build - builds the docker image for local testing\n\n"
+  printf "env build - Installs the npm dependencies and builds the library for local use\n\n"
 
   printf "%s\n" "Usage:"
   printf "  env build\n"
@@ -296,6 +297,27 @@ env_npm_usage() {
   printf "%s\n" "Usage:"
   printf "  env npm [--] [...]\n"
   printf "  env npm --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+env_open_usage() {
+  printf "env open - opens the project in the browser\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  env open\n"
+  printf "  env open --help | -h\n"
   echo
 
   # :command.long_usage
@@ -800,8 +822,8 @@ env_logs_command() {
 env_build_command() {
 
   # _env/src/build_command.sh
-  SERVICE_NAME=app
-  $DOCKER_COMPOSE_EXECUTABLE build ${SERVICE_NAME}
+  dockerSsh app "npm install"
+  dockerSsh app "npm run build"
 
 }
 
@@ -838,7 +860,15 @@ env_npm_command() {
   # _env/src/npm_command.sh
   CMD="${other_args[*]}"
 
-  dockerSsh node "npm ${CMD}"
+  dockerSsh app "npm ${CMD}"
+
+}
+
+# :command.function
+env_open_command() {
+
+  # _env/src/open_command.sh
+  open "${DOCKER_PROJECT_PROTOCOL:-http}://${DOCKER_PROJECT_DOMAIN:-${DOCKER_PROJECT_IP:-localhost}}:${DOCKER_PROJECT_PORT:-8000}"
 
 }
 
@@ -939,6 +969,13 @@ parse_requirements() {
       action="npm"
       shift
       env_npm_parse_requirements "$@"
+      shift $#
+      ;;
+
+    open)
+      action="open"
+      shift
+      env_open_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1512,6 +1549,51 @@ env_npm_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+env_open_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        env_open_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="open"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   declare -g version="1.0.0"
@@ -1570,6 +1652,7 @@ run() {
     "rebuild-cli") env_rebuild_cli_command ;;
     "ssh") env_ssh_command ;;
     "npm") env_npm_command ;;
+    "open") env_open_command ;;
   esac
 }
 
